name: Terraform CICD Pipeline

on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: Terraform-Infrastructure-Management.
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.9.5
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: Terraform-module
      - name: Terraform Format
        id: fmt 
        run: terraform fmt -check
        working-directory: Terraform-module
      - name: Terraform validate
        id: validate
        run: terraform validate
        working-directory: Terraform-module
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: Terraform-module
      - name: Terraform apply
        id: apply 
        run: terraform apply -auto-approve
        working-directory: Terraform-module
      
        

      